### ISSUE TITLE
A-Frame style declarative abstraction layer

### ISSUE THREAD

**Issue by edsilv** [MozillaReality/ecsy#10]
Hi,

Exciting project!

I really like how you're making this lib reactive and framework agnostic off the bat. It occurs to me though for folks wishing to transition to this from A-Frame it could help to have a declarative abstraction layer over it?

I've been working on an experimental build system for A-Frame using TypeScript, Webpack, and custom elements v1: https://github.com/edsilv/aframe-ts-webpack

Perhaps this could consume ecsy to provide all of the underlying logic, maintaining separation of concerns and giving A-Frame users a way to pick it up quickly?

**Comment by edsilv** [comment]
Also:

> Systems have just behaviour, without storing state

We're using Redux to manage state and reactively rendering A-Frame tags in jsx based on that. Seems like your approach would lend itself to that?

**Comment by edsilv** [comment]
I'd be really interested to explore the possibility for a "WebECS" standard HTML/JSON encoding for this and A-Frame at the presentation level. Maybe there's the potential to create a working group. It's probably something the game and web development industries could mutually benefit from.

**Comment by fernandojsg** [comment]
Closing it. We just updated the goals in this repo https://github.com/MozillaReality/ecsy#goals and even so we think this is a really cool project to build around ecsy, it won't be part of ecsy "core" as is, but instead should be build outside this repo in another one like `ecsy-three`, `ecsy-babylon` or so.
