### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by fernandojsg** [MozillaReality/ecsy#101]
Events were initially implemented but have been removed as we could use components and queries for the use cases we had in mind.
I just want to document the previous implementation here in case we want to revisit it in the future.

The way to define events was as for queries, using an static attribute on the system's class:
```js
class TestSystem extends System {}

TestSystem.events = {
  eventNewName: "eventOriginalName"
};
```

The `events` attribute does a map from the event's name to the name we would like to use on the system (of course it could just be the same name).

To use the event we could just iterate on the `this.events.*` as we do with `this.queries.*`:
```js
class TestSystem extends System {
  execute() {
    this.events.eventNewName.forEach(parameters => {
      // Do whatever you need with the parameters
    });
  }
}
```

In order to emit an event, you will emit them globally in the world:
```js
world.emitEvent("eventOriginalName", parameters);
```

The advantage of using events this way is that the events are queued the same way queries' events are handled, so we make them predictable as they will get handled when the system will get executed, and won't interrupt the execution when the event is triggered as happens with event listeners or callbacks.

**Comment by ikendoit** [comment]
Hello @fernandojsg , 

For my use case at the moment, I am receiving a world-snapshot from the game server, and need to update the components of entities described in that Snapshot. 

Having this event based system-invocation will make it much easier as I can do:
```
  // handle web socket message
  function handleWorldSnapshotFromServer(worldSnapshot) {
      this.world.emitEvent("worldSnapshotSync", worldSnapshot); // invoke a system to update components according to snapshot from server
  }
```

Is this an use-case that you guys have considered? If so, what is the best-practice for situations like this?
