### ISSUE TITLE
Improve Babylon.js demo

### ISSUE THREAD

**Issue by deltakosh** [MozillaReality/ecsy#105]
Hello code for Babylon.js should use mesh.clone to make sure all boxes share the same geometry. So you could 10000 of them;)

On other note maybe using instances? Like here: 

https://www.babylonjs-playground.com/#PCY1J

**Comment by fernandojsg** [comment]
@deltakosh yeah! I had that in my TO-DO list as I'm quite new to babylon so I knew it should be a better way to do it :) Looking forward to include more examples using your api!
thanks for the PR

Closed by #106
