### ISSUE TITLE
System API Docs

### ISSUE THREAD

**Issue by dannyfritz** [MozillaReality/ecsy#113]
The [System docs](https://ecsy.io/docs/#/api/classes/syst) appear to be missing a lot of information. Namely `static queries`, `init()`, and `execute(delta, time)`.

How would I go about adding in that information? Is this page auto-generated? Or would I go in and modify it manually?

![firefox_2019-10-09_09-20-18](https://user-images.githubusercontent.com/315788/66495180-1328eb00-ea76-11e9-836e-8755a6f5928e.png)

**Comment by brianpeiris** [comment]
Thanks for offering to help. These docs are generated from the typescript definition files we have for each class. In this case, https://github.com/MozillaReality/ecsy/blob/dev/src/System.d.ts

When you run `npm start`, it also regenerates the docs on change.

**Comment by joshmarinacci** [comment]
can this be merged yet?

**Comment by fernandojsg** [comment]
Waiting for review by @robertlong on the typescript types PRs
