### ISSUE TITLE
Bad constructors when using as a node module

### ISSUE THREAD

**Issue by xevrem** [MozillaReality/ecsy#119]
I'm having an issue with the exported modules from ECSY not instantiating correctly.
i've added ECSY to my project via `npm i ecsy` or `yarn add ecsy`.
when i try to use the demo code as a standalone `js` file that is loaded in at rutime i.e., like any modern babel & webpack/parcel project  `<script type="application/javascript" src="./src/index.js"></script>` in my `index.html`

I get the following depending on how it is imported:

`import {World, System, TagComponent } from 'ecsy'`:
- `Uncaught TypeError: _index.World is not a constructor`

`import {World, System,TagComponent} from 'ecsy/build/ecsy.module'`:
- `Uncaught TypeError: Class constructor System cannot be invoked without 'new'`

right now, the only way it works is if i run the project as an inline-script via the web-module (which is unrealistic for real-world use).

What is the correct way to use ECSY as a node module for bundled application builds?

**Comment by robertlong** [comment]
Hey @xevrem I think the first way should work. Maybe this boilerplate project will help you get setup with webpack:

https://github.com/MozillaReality/ecsy-webpack-boilerplate

Let me know if you still are having issues.

**Comment by xevrem** [comment]
ooh! thanks, I'll give it a go the next chance I have!

**Comment by xevrem** [comment]
yay! it appears it is working!
you can see my experiments with it and pixi.js [here](https://github.com/xevrem/ecs-pixi) as well as with my own variation of an [ecs-framework](https://github.com/xevrem/ecs-framework) [feel free to steal ides :)]

side note: still does not appear to like [parcel](https://parceljs.org/) :(

**Comment by joshmarinacci** [comment]
can we close this?

**Comment by AndrewJakubowicz** [comment]
You can hack it to work in parcel by adding `"browserslist": ["> 5%"]` to the package.json file. [[reference](https://github.com/Polymer/pwa-starter-kit/issues/309#issuecomment-454591896)].

**Comment by xevrem** [comment]
nice, ended up using something similar in a `.babelrc` everything appears to work ok now

**Comment by jamieowen** [comment]
I had the same error with typescript + webpack.  I was using ts-loader with webpack but couldn't get this working.

I had to switch to the @babel/preset-typescript ( via babel-loader ) and add the > 2% to preset-env arguments.

```
    [ '@babel/preset-env', { 
      targets: {
        browsers: ["> 2%"]
      }
    }],   
```

Fun times!

**Comment by snowfrogdev** [comment]
I also had this problem when using Parcel and TypeScript. @AndrewJakubowicz has properly demonstrated the fix for this. It is not a problem with ecsy but rather with the way external tools are configured to transpile and package it, and as such I do believe we can close this issue. @fernandojsg

**Comment by fernandojsg** [comment]
Thank you @snowfrogdev crossing it now.
