### ISSUE TITLE
add remove component ordering issue

### ISSUE THREAD

**Issue by joshmarinacci** [MozillaReality/ecsy#120]
I have some code where I want to remove a component from an entity, then add the same type of component back. For both the add and remove there are listen queries that should be run. I'm removing before adding, but unfortunately, the remove query is being called after the add query.

I can work around this bug by instead calling the remove inside of a set timeout, and then the add inside of an even longer set timeout to enforce the ordering. This shouldn't be necessary.

**Comment by fernandojsg** [comment]
@joshmarinacci could you please provide an example code on what are you doing and the use case, I believe I don't fully understand what you mean. Are you adding/removing components while iterating the list of entities so it get mutated?

**Comment by joshmarinacci** [comment]
It’s not entirely clear. Yes I think I might be. Though it’s to a new entity.

**Comment by joshmarinacci** [comment]
Nevermind.  It was a bug in my code. Two different queries were being executed from the same add so I was doubling up the behavior.
