### ISSUE TITLE
Add warning when registering component under name that is already in use

### ISSUE THREAD

**Issue by nickschot** [MozillaReality/ecsy#123]
I autoregister sets of components and it has happened that I forgot to rename one or that a duplicate exists for another reason. A (debug) warning when adding a component under a name that is already in use should cover this.

Same for systems maybe?

When I have time I can make a PR.

**Comment by fernandojsg** [comment]
Thanks for the suggestion, that's quite useful indeed.
I just implemented it and pushed it to `dev` branch.
I included two tests:
https://github.com/MozillaReality/ecsy/blob/dev/test/unit/SystemManager.test.js
https://github.com/MozillaReality/ecsy/blob/dev/test/unit/ComponentManager.test.js
