### ISSUE TITLE
Component name case sensitive detection?

### ISSUE THREAD

**Issue by shang-huang** [MozillaReality/ecsy#124]
I get wrong entity in the system `execute()`, when listen to a component name has other lower/upper case component name.

[example code](https://gist.github.com/shang-huang/f4cb1391078f11a1634d39be3eb91ade)
Example above is 
a system **S** listens **B** component and 
a system **s** listens **b** component in the world;
when I create an entity add **B**, both systems will show they get entity has **B**.

**Comment by fernandojsg** [comment]
@shang-huang thanks for reporting it! I already fixed it on `dev` branch and it will be added to the next release.
I've added also a test case based on your code
https://github.com/MozillaReality/ecsy/blob/dev/test/unit/system.test.js#L814-L855

Thanks!
