### ISSUE TITLE
Components name case sensitive detection?

### ISSUE THREAD

**Issue by shang-huang** [MozillaReality/ecsy#129]
I get wrong entity/entities in the system execute(), when listen to multiple components which have names in lower/upper case.

[example code](https://gist.github.com/shang-huang/6a98996e1ae86ecbf0ace9070c3664df)
Expected: {B: B, b: b}
Actual: {B: B, b: B}

**Comment by fernandojsg** [comment]
@shang-huang thanks for reporting! and sorry for the late reply :) 
I fixed the issue on `dev` and I added a test case for that. I'll soon deploy a new package release.
https://github.com/MozillaReality/ecsy/blob/dev/test/unit/system.test.js#L855-L884
