### ISSUE TITLE
Accessing the world within a System

### ISSUE THREAD

**Issue by hwaterke** [MozillaReality/ecsy#131]
Is it good practice to access the world inside a System?
The type definitions do not expose it.

What I mean is something like this:
```
class SpawnSystem extends System {
  execute(delta, time) {
    // Some logic
      this.world.createEntity() // ...
  }
}
```

If not, how would you achieve something similar i.e. creating new entities during the life of the World?

**Comment by Nebual** [comment]
Ecsy's type definitions are pretty incomplete at the moment, but I think the intention is to expose the world.
https://github.com/nejcjelovcan/ecsy/commit/2ee42045c012528c747a497fe556552f754c8b96 adds a typedef for it, I've messily combined it and the other types PR on https://github.com/Nebual/ecsy/commits/staging

**Comment by fernandojsg** [comment]
You are right, is ok to use `world`. If we find that this could cause problems in the future we will just revisit it and add an explainer.
