### ISSUE TITLE
SystemStateComponent Number counted in EntityManager, not in Entity, leading to unkillable Entities

### ISSUE THREAD

**Issue by totallyRonja** [MozillaReality/ecsy#137]
I ran into a problem recently where removing and adding entities would increase the amount of entities rapidly, without changing the amount of components. All of the entities lying around were completely empty and marked as not alive.
It turns out that in the EntityManager the amount of all SystemStateComponents is tracked and if any exist on any entity, the entity cannot be deleted.

This is easy to reproduce by opening the System State Components demo, creating a few entities, giving all of them sprite components and then deleting enemies, the component count in the debugger will drop, but the entity count will not. Only after all components are deleted entities can be deleted again.

https://github.com/MozillaReality/ecsy/blob/5cca872f55f8f1a3ee319de5dd6978ff056d6b6d/src/EntityManager.js#L133

**Comment by fernandojsg** [comment]
Good catch! and thanks for the PR
