### ISSUE TITLE
registerSystem by passing instance instead of constructor / type

### ISSUE THREAD

**Issue by leon** [MozillaReality/ecsy#145]
I would like to be able to construct my systems myself.
This is because I need to pass external dependencies into the system.

In my case from Angulars dependency injection system.
But I can see other use cases where I would want to create the system my self.

Should we simply change how systems are created by making the user new up an instance and pass it.
and then move the constructor logic to a function that gets called when we add it to the world.

What do you think?

**Comment by Kieirra** [comment]
You can pass parameters when registering System and override constructor to retrieve them so for me you can already do this.

`new World().registerSystem(EngineSystem, { myParams })`

And : 

`class AIScriptSystem extends System {
  constructor(world, attributes) {
      super(world, attributes);
      this.myParams = attributes.myParams;
  }`
   
...
}

**Comment by leon** [comment]
Yes but if use a dependency injection system such as angular.
Then I have no control over the creation of the class.

I would rather allow the user to create the instances of both systems and components and then add them. It goes more in line with how three.js for example has its api.

What was the thoughts behind the current architecture?
Im not saying the current is wrong, I’m just curious of why the it was chosen 😁

**Comment by mistakenot** [comment]
When I do this in TypeScript, I get a compilation error over the call to `super(world, attributes)`, "Expected 0 arguments, but got 2". Is this intentional, or is it worth me submitting a fix for? This constructor signature isn't defined in the type file.

**Comment by patrickjm** [comment]
@mistakenot I'm not a maintainer, but I think looks like a fix. I'm having the same problem.

`System.d.ts` has no constructor definition, but here's the JS constructor:

```js
export class System {
  ...
  constructor(world, attributes) {
    this.world = world;
    this.enabled = true;
    ...
  }
  ...
}
```

There is no way to have your System implement `SystemConstructor<YourSystem>` that I'm aware of, as constructors belong to the class, and interfaces describe an instance of the class. I think the only way would be using global declarations, which imo belong in the lib.

My current fix is the following hack 😄 

```typescript
constructor(world: World, state: SceneState) {
    // @ts-ignore 
    super(world, state);
}
```

@fernandojsg thoughts?

**Comment by fernandojsg** [comment]
Will work for you all the overloading of the constructor as exposed by @patrickjm ?
```javascript
constructor(world, attributes) {
   super(word, attributes);
   // do whatever you want here
}
```
(This will need this PR to fix the issue with the typescript definitions: https://github.com/MozillaReality/ecsy/pull/155)

Not sure if you checked this two proposals by @FostUK to access easily the `attributes` when registering a system: https://github.com/MozillaReality/ecsy/pull/151 (TL;DR we will call `init(attributes)` so you can do whatever you want there with these), and https://github.com/MozillaReality/ecsy/pull/152  (TL;DR world[attributeName] = attributes[attributesName] for all attributes, so you could access them whenever you want.

Is there any use case that won't be covered with any of these changes?

**Comment by fernandojsg** [comment]
Closing it as currently there are already options to provide data to the system via init() or constructor
