### ISSUE TITLE
Why registerComponent?

### ISSUE THREAD

**Issue by simonihmig** [MozillaReality/ecsy#147]
Looking through the sources I wonder why this method exists?

It is not mentioned in the guides, only the API docs, and its use is not required, as a newly used Component gets auto-registered by the ComponentManager. 

But also inside the ComponentManager I see a bit of housekeeping going on:
https://github.com/MozillaReality/ecsy/blob/dev/src/ComponentManager.js#L18-L19

There is the `Components` hash, and the `numComponents` counter, but it seems both are unused outside of the class, and don't really service a meaningful purpose inside the class, AFAICT. (e.g. the counter is never read from)

So do I miss something, or could this be removed?

**Comment by fernandojsg** [comment]
You are right, currently `registerComponent` is not being actively used, although that's something that will change with some incoming iterations on the API. I added that function initially thinking on tooling (so you could have all the list of components available in a manager somewhere), but also for validation of the components themselves, and, with the new changes, it will be used also to create the managers or pooling needed for these components before even using them.
I'll be sharing the ideas around it in incoming issues.
