### ISSUE TITLE
Why no "getEntityById" lookup?

### ISSUE THREAD

**Issue by mistakenot** [MozillaReality/ecsy#148]
I'm curious if there was a design decision not to include something like a `world.getEntityById()`. Method.

My use case involves ray tracing in three.js. The three.js ray tracer hits an object and returns an instance of three's `Object3D` class, which has a unique ID. What I want to do is find the existing ecsy entity associated with this object so that I can add / remove components.

At the moment there is no apparent way for me to do this, unless I somehow attach the ecsy entity to the Object3D instance itself, which feels like a bit of an antipattern.

**Comment by zanchi** [comment]
I can't speak on why it's not included, but I also found myself needing this. In my case, I needed to update entities when a message is received from the server with the id of the entity to update. You might've already come up with a solution, but I figured I'd share mine for posterity. Basically, I took a cue from the suggestions in #107 and maintained a separate data structure in the system that needs it, in this case just a hashmap.

Something like this would probably work:

```javascript
class SomeSystem extends System {
  raytraceables = new Map()

  execute() {
    for (const entity of this.queries.raytraceable.added) {
      const { someId } = entity.getComponent(Raytraceable)
      this.raytraceables.set(someId, entity)
    }

    const id = doRaytrace()
    const entity = this.raytraceables.get(id)
  }
}

SomeSystem.queries = {
  raytraceable: {
    components: [Raytraceable]
    listen: {
      added: true
    }
  }
}
```

Hope this is helpful 😄

**Comment by mistakenot** [comment]
Yup, that is what I ended up doing in quite a few places. Was just curious if it was an anti-pattern, or would interfere with the lifecycle management of the entity. Seems to be working so far! Thanks.
