### ISSUE TITLE
ECS Design Question - Weapons, Projectiles, Collision

### ISSUE THREAD

**Issue by nickyvanurk** [MozillaReality/ecsy#172]
Hi there,

This is probably not the right place to ask but I give it a shot anyways. It's my first time using an ECS for a game I'm building (follow my progress here: https://nickyvanurk.com/void/). My question is regarding systems design. I want a spaceship that can have multiple weapons with different projectiles, those projectiles can also collide with other objects and be destroyed and eventually spawn some effect.  Does anyone have any suggestions on how one would go about implementing this in an ECS way? What I have currently is a Weapons component which has an array of Weapon components and a single WeaponSystem. My collision logic is still done in my PhysicsSystem.

Source code: https://github.com/nickyvanurk/3d-multiplayer-browser-shooter/tree/master/client/src

Thank you in advance!

P.S I read all the source code of ecsy, ecsy-three, all examples. Still don't have a proper clean solution. I feel I might make it more complex than it needs to be.

**Comment by totallyRonja** [comment]
The correct place to ask would probably be the forum: https://discourse.mozilla.org/c/mixed-reality/ecsy

that being said, the main limitation of the ECS pattern is that you can only have one instance of a component on an entity. So my gut feeling is to create one entity for each weapon and then you can give that a weapon component, a local location, a parent object, a component to reference the physics representation. And then yeah you can reference those weapon entities via an array in a component in your main ship entity.
Your systems should then be whatever systems you need to change those entities in the ways you need to. What needs to happen to make the parent child relationship between spaceship and weapons to work. Probably a system to handle input and make the weapons actually shoot.

So yeah just glancing over it what you have already looks pretty good. You could probably abstract some stuff away and make more different components and systems to be able to reuse the components later, but the most important thing is that you can make your code do what you need it to, not to be "correct" by some arbitrary standard.

**Comment by nickyvanurk** [comment]
Thank you very much. The way I described it currently works indeed. You can follow my progress here: https://nickyvanurk.com/void/ Will be a cool ecsy demo for sure.

**Comment by fernandojsg** [comment]
I was doing something similar to the array of components too. Per design you can't have multiple components instances per entity, but you can have a component with an array of elements.
I was doing something like that when I needed multiple sounds within the same entity.

By the way your demo looks really cool! looking forward to see more of it! :)

Closing it now so we could move this type of discussions to the forum.

Thanks!
