### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by fernandojsg** [MozillaReality/ecsy#178]
I started working on adding some benchmarks to ecsy #177 
I'll write down here the list of things we should benchmark to keep track of the TO-DO
The idea is that the tool could generate a JSON report that could be used to compare across two branches to see if we are getting any regression in performance.

**Comment by robertlong** [comment]
Maybe we could automate this with github actions or circleci with something like this?
https://github.com/rhysd/github-action-benchmark

**Comment by fernandojsg** [comment]
Ops that looks really cool, I didn't know about it. I'll take a look, thanks for sharing

**Comment by fernandojsg** [comment]
Closing this as we already have benchmarks, and created a new issue to talk specifically about how to include it in CI instead of just local runs #220
