### ISSUE TITLE
Asynchronous init on systems

### ISSUE THREAD

**Issue by fernandojsg** [MozillaReality/ecsy#20]
Currently every system is expected to have a synchronous `init()`, but some systems could be async and it could be nice to have some examples and best practices around it

**Comment by joshmarinacci** [comment]
Do you mean for things like loading a GLTF file?

**Comment by fernandojsg** [comment]
I had more in mind systems that will need to initialize code in order to run, for example the Physics system using ammo.js as you need to load the wasm module asynchronously, and can't just start executing it until you are done there

**Comment by fernandojsg** [comment]
We could already implement this logic without need to have a system async per se, but just implement the logic in init or execute
