### ISSUE TITLE
Component types prevent property access in TypeScript

### ISSUE THREAD

**Issue by royvandewater** [MozillaReality/ecsy#211]
I can't get access to the properties of a component when using TypeScript. I created an [example glitch](https://glitch.com/edit/#!/opalescent-zippy-result) that shows the compilation error (in example.ts).

It looks like the parameterized type is passed to the constructor, but not used to define what is available as public instance properties.

I get the error: 

```
example.ts(19,30): error TS2339: Property 'x' does not exist on type 'Foo'.
``` 

using the following example code:

```ts
import { Component, System, Types } from 'ecsy'

interface Position {
  x: number;
  y: number
}

class Foo extends Component<Position> {}

Foo.schema = {
  x: { type: Types.Number },
  y: { type: Types.Number },
}

class Bar extends System {
  execute(_delta: number, _time: number): void {
    this.queries.foo.results.forEach(entity => {
      const foo = entity.getComponent(Foo) // <-- Correctly returns type Foo
      console.log('foo', foo.x) // <--- where the compilation error happens
    })
  }
}

Bar.queries = {
  foo: { components: [Foo] }
}
```

**Comment by robertlong** [comment]
Try using:

```typescript
class Foo extends Component<Foo> {
  x: number;
  y: number;
}

Foo.schema = {
  x: { type: Types.Number },
  y: { type: Types.Number },
}
```

The generic argument (`Component<T>`)  is for typing the props passed into the constructor.

**Comment by royvandewater** [comment]
Ah, I didn't think to pass the class into itself, that makes sense! Thank you!

**Comment by royvandewater** [comment]
I tried to define the class in terms of itself and it caused it to become impossible to call the constructor.

```
class Foo extends Component<Foo> {
  x: number
}
```

This component can't be constructed since the constructor now requires a preexisting instance, both `world.createEntity().addComponent(Foo, { x: 0 })` & `new Foo({ x: 0 })` return the error:

```Argument of type '{ x: number; y: number; }' is not assignable to parameter of type 'false | Foo | undefined'.
  Type '{ x: number; y: number; }' is missing the following properties from type 'Foo': copy, clone, reset, dispose
```

**Comment by robertlong** [comment]
@royvandewater can you install ecsy from the dev branch? @fernandojsg I think we should publish a new build soon to keep people from running into these issues.

**Comment by fernandojsg** [comment]
Please give it a try to 0.3.2, I just published the new release and it should fix these issues. Feel free to reopen it again if he problem continues. Thanks!

**Comment by royvandewater** [comment]
That did it, thank you!

**Comment by fernandojsg** [comment]
Cool! Thanks for letting us know ;)

**Comment by vegeta897** [comment]
Is there still no better way of doing this? Writing the types twice feels wrong and prone to mistakes.

**Comment by ulyssesp** [comment]
Was this reverted in a recent change? I'm on 0.4.2 and need to define the types thrice for it to work. 

(side note: awesome library, love that you're taking these concepts to js)
