### ISSUE TITLE
Add "single" modifier to the queries

### ISSUE THREAD

**Issue by fernandojsg** [MozillaReality/ecsy#29]
Add a simple syntactic sugar so you can define a `single` modifier on the queries to define that the query should expect just one item out of that query (as a way to replace singleton too).
Currently it could be just a prettier way to access that entity instead of doing `this.queries.renderer[0]`, but we can imagine that in the future it could help doing some optimizations for this kind of queries in under the hood if needed.
Also together with https://github.com/fernandojsg/ecsy/issues/28 will make using the singleton concept easier.

```javascript
class TestSystem extends System {
  init() {
    return {
      queries: {
        meshes: { components: [Mesh] }
        renderer: { components: [RendererComponent], single: true }
      }
    };
  }

  execute(delta) {
    let meshes = this.queries.meshes;
    meshes.forEach(mesh => {
      this.queries.renderer.renderMesh(mesh);
    });
  }
}
```

**Comment by joshmarinacci** [comment]
I would use this. I do this all the time. However, we need to handle the case where the singleton hasn't been created yet.

**Comment by fernandojsg** [comment]
@joshmarinacci you can combine it with the `mandatory` attribute (https://github.com/fernandojsg/ecsy/issues/28) so your execute method won't be called if there's no match yet

**Comment by fernandojsg** [comment]
Reopening it until we find an easy and fast way to implement it https://github.com/fernandojsg/ecsy/pull/45

**Comment by fernandojsg** [comment]
This is just syntactic sugar that will require mutate of the queries arrays, so i'm closing it by now, we could revisit if needed in the future
