### ISSUE TITLE
world.createComponent to create components without adding them to an entity

### ISSUE THREAD

**Issue by fernandojsg** [MozillaReality/ecsy#81]
Currently is possible to add a component by passing the component class and an object to replace the default values:
```javascript
entity.addComponent(ComponentA);
entity.addComponent(ComponentB, {value: 23, other: 'test'});
```

It would be interesting to be able to request a component without adding it to an entity automatically:
```javascript
var component = world.createComponent(ComponentB);
component.value = 23;
component.other = 'test';

entity.addComponent(component);

// You could still do this the "old" way
entity.addComponent(ComponentA); // Just some sugar to detect the component
```

**Comment by wingyplus** [comment]
What’s benefit from this approach?

**Comment by fernandojsg** [comment]
This is based on a concept of `attaching` / `detaching` entities or components from the world, so they are being created but not being added to any query.
But this is already outdated as we were thinking about other ways to provide that functionality that will get added soon to the repo. Closing it
