### ISSUE TITLE
Add links on the examples' source code on github

### ISSUE THREAD

**Issue by fernandojsg** [MozillaReality/ecsy#88]
and also to glitch?

**Comment by snowfrogdev** [comment]
@fernandojsg this seems like a simple enough task that I'd be willing to tackle. Although I might need a bit of guidance. What links would you like added and where?

**Comment by fernandojsg** [comment]
@snowfrogdev sorry for the delay! That was already solved by adding the `(source)` link next to the example name. 
Although another option could be to add a icon on the bottom right as three.js does here: https://threejs.org/examples/#webgl_effects_ascii
