### ISSUE TITLE
Clarify public, documented API

### ISSUE THREAD

**Issue by brianpeiris** [MozillaReality/ecsy#98]
While writing out the rest of the generated API docs for #97, I wasn't sure if I should include these members in the docs:

- Entity: `alive, id, queries, getComponents, getRemovedComponents, getComponentsToRemove, getComponentTypes, hasRemovedComponent, reset`
- System: `enabled, canExecute, clearEvents, toJSON`
- World: `enabled, eventDispatcher, eventQueues, emitEvent, addEventListener, removeEventListener, getSystem, getSystems, stats`

Some of these members seem like they are internal or are only used in test code.

I also noticed that IntersectionSystem in the canvas example has a `stop` method which implies that it will be called by the framework, but that doesn't seem to be the case.

**Comment by fernandojsg** [comment]
- Entity: 
  - public: `id, getComponents, getRemovedComponent, getComponentsToRemove, getComponentTypes, hasRemovedComponent`
  - private: `alive, queries, reset`
- System: 
  - public: `enabled`
  - private: `canExecute, clearEvents, toJSON`
- World: 
  - public: `enabled, getSystem, getSystems`
  - private: `eventDispatcher, eventQueues, stats`
  - deprecated: `emitEvent, addEventListener, removeEventListener` these will get deleted soon

Re the stop, you are right. I opened an issue for that https://github.com/MozillaReality/ecsy/issues/99

**Comment by brianpeiris** [comment]
Cool, thanks for clearing that up. 
I'm surprised that `queries` should be public, when do you expect users to care about it? Presumably you don't want them mutating that array themselves?
Also a bit surprised that getRemovedComponents and getComponentsToRemove are necessary. What's the use case there?

**Comment by fernandojsg** [comment]
Sorry the `getComponentsToRemove` should not be public, the  `getRemovedComponents` could be used on a reactive query that is listening for `removed` so you want to know which component has been removed there.
What do you mean with `queries` being public? in Entities is private

**Comment by brianpeiris** [comment]
Oh, sorry, I just misread where `queries` was. That makes sense 👍
